{pkgs-stable, ...}: {
  environment.systemPackages = with pkgs-stable; [
    (vimPlugins.nvim-treesitter.withPlugins (plugins: [
      # Combine allGrammars with explicitly listed plugins if needed
      # (tree-sitter.allGrammars) ++ [ ... ]
      tree-sitter.allGrammars
      tree-sitter-c
      tree-sitter-cpp
      tree-sitter-dockerfile
      tree-sitter-fish
      tree-sitter-go
      tree-sitter-html
      tree-sitter-svelte
      tree-sitter-json
      tree-sitter-lua
      tree-sitter-nix
      tree-sitter-sql
      tree-sitter-python
      tree-sitter-r
      tree-sitter-dockerfile
      tree-sitter-java
      tree-sitter-regex
      tree-sitter-rust
      tree-sitter-toml
      tree-sitter-vim
      tree-sitter-yaml
      tree-sitter-toml
    ]))
    neovim
    wget
    lemminx
    nil
    svelte-language-server
    gopls
    nixd
    mesonlsp
    eza
    fish
    starship
    sassc
    ccls
    sqls
    dockerfile-language-server-nodejs
    jdt-language-server
    google-java-format
    vscode-langservers-extracted
    llvmPackages_19.clang-unwrapped
    gcc14
    nodejs_22
    typescript-language-server
    sass
    lua54Packages.luarocks_bootstrap
    stylua
    typescript
    nodejs-slim_22
    fish-lsp
    python312Packages.python-lsp-server
    pyright
    rust-analyzer
    marksman
    tailwindcss-language-server
    bash-language-server
    shfmt
    prettierd
    lua-language-server
    yarn
    pnpm
    cmake
    ninja
    libgdiplus
    wl-clipboard
    polkit
    tree-sitter
    pciutils
    vulkan-tools
    cloudflare-warp
    dynamips
    ubridge
    busybox
    inetutils
    libvirt
    virt-viewer
    p11-kit
    openssl
    lftp
    cloudflared
    lazydocker
    home-manager
    forgejo-runner
    attic-client
    attic-server
    # Stirling depends
    python3
    jdk21
    gnumake
    libgcc
    automake
    autoconf
    libtool
    pkg-config
    zlib
    leptonica
    jbig2enc
    libreoffice
    tesseract
    poppler_utils
    # Ends
  ];
}
