name: "Build Packages for Cachix"
on:
  workflow_call:
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v15
      with:
        name: myamusashi
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .
