name: "Build Packages for Cachix"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
    - uses: actions/checkout@v4
    - name: Update packages and Install sudo (if not present)
      run: |
        sudo apt-get update && sudo apt-get full-upgrade -y
        sudo apt-get install -y sudo
      env:
        CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: myamusashi
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build and push to Cachix
      run: |
        nix build | cachix push myamusashi

