name: "Build Packages for Cachix"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install sudo
      run: |
        apt-get update && apt-get full-upgrade -y
        apt-get install -y sudo
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: myamusashi
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build | cachix push myamusashi
